env: flex
runtime: python
runtime_config:
  python_version: 3 # 3.7.2

entrypoint: gunicorn -b :$PORT project.wsgi

beta_settings:
  cloud_sql_instances: "district-stage:us-central1:district-main"

env_variables:
  GCP_STAGE: "true"

skip_files:
  - files/
  - frontend/
  - static/
  - node_modules/
  - ^Makefile$
  - ^venv$
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cpu_utilization:
    target_utilization: 0.5

readiness_check:
  #path: "/api/status"
  check_interval_sec: 120
  timeout_sec: 5
  failure_threshold: 5
  success_threshold: 2
  app_start_timeout_sec: 1500

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10